import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles((theme) => ({
  backdrop: {
    position: 'fixed',
    width: '100%',
    height: '100vh',
    zIndex: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(32,32,32,0.6)',
    backdropFilter: 'blur(12px)',
  },
  backdropLoading: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 7,
    display: 'grid',
    placeContent: 'center',
  },
  loading: {
    zIndex: 9,
    display: 'grid',
    placeContent: 'center',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    boxShadow:
      'rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px',
  },
  card: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '90%',
    width: 625,
    backgroundColor: '#F9F9F9',
    borderRadius: 30,
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.05)',
    position: 'relative',
    padding: '40px 71px 40px 71px',
    '& h2': {
      fontFamily: "'Baloo 2', cursive",
      fontSize: 40,
      fontWeight: 'normal',
      margin: 0,
      color: 'rgba(18, 18, 18, 0.8)',
    },
  },
  botaoFechar: {
    zIndex: 11,
    position: 'absolute',
    top: 40,
    right: 40,
    cursor: 'pointer',
  },
  infoCliente: {
    boxSizing: 'border-box',
    width: '100%',
    fontSize: 14,
    fontFamily: 'Montserrat',
    fontWeight: 400,
    marginTop: 5,
    marginBottom: 5,
    color: '#3E3E3E',
    '& > span': {
      fontWeight: 700,
      color: '#D13201',
    },
  },
  produtos: {
    display: 'flex',
    flexDirection: 'column',
    gap: 25,
    height: 230,
    overflowY: 'scroll',
    marginBottom: 25,
    marginTop: 25,
  },
  footer: {
    marginTop: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 15,
    '& > button': {
      all: 'unset',
      cursor: 'pointer',
      backgroundColor: '#D13201',
      padding: '13px 50px',
      borderRadius: 20,
      color: 'white',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontSize: 14,
      '&:disabled': {
        backgroundColor: '#BABABA',
        cursor: 'not-allowed',
      },
    },
  },
  footerTexto: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
    fontFamily: 'Montserrat',
    color: '#525459',
    paddingTop: 25,
    borderTop: '1px solid #D5D5D5',
    margin: 0,
    '& > p': {
      fontWeight: 'normal',
      fontSize: 14,
      margin: 0,
    },
    '& > h3': {
      fontWeight: 600,
      fontSize: 24,
      margin: 0,
    },
  },
}));

export default useStyles;
